/* Code Life v2 — Code City map build. No scenery animation, no invented extra pets.
   Original local-only game state. HTML/CSS/JS lessons sourced from existing curriculum.js;
   Python/SQL road sections are visually planned, NOT falsely represented as ready lessons. */
(()=>{'use strict';
const root=document.querySelector('#city-root');if(!root)return;
const KEY='code-life-v2:city-state';const PET_KEY='code-life-v2:onboarding:pet';
const PET_NAMES={'pixel-pup':'Pixel Pup','byte-cat':'Byte Cat','nova-owl':'Nova Owl','loop-fox':'Loop Fox','chip-bunny':'Chip Bunny','glitch-dino':'Glitch Dino'};
const ZONES=[
  {id:'html',name:'HTML Town',sign:'WELCOME TO',accent:'#64dfff'},
  {id:'css',name:'CSS District',sign:'NOW ENTERING',accent:'#c29bff'},
  {id:'js',name:'JavaScript City',sign:'WELCOME TO',accent:'#f8d978'},
  {id:'python',name:'Python Lab',sign:'NOW ENTERING',accent:'#78f5df'},
  {id:'sql',name:'Data Vault',sign:'WELCOME TO',accent:'#a3c8ff'}
];
// No made-up level counts for later towns: their detailed lesson plans are pending.
const PLANNED={python:[],sql:[]};
const bodyData=window.CODE_LIFE_DATA||{lessons:[]};
let n=0;const nodes=[],segments=[];
for(const zone of ZONES){
 const lessons=['html','css','js'].includes(zone.id)?bodyData.lessons.filter(l=>l.track===zone.id):PLANNED[zone.id].map((title,i)=>({id:zone.id+'-'+(i+1),title,track:zone.id,planned:true}));
 const own=lessons.map(lesson=>({number:++n,zone,kind:'lesson',lesson,planned:!!lesson.planned}));
 if(!PLANNED[zone.id])own.push({number:++n,zone,kind:'boss',lesson:null,planned:false});
 nodes.push(...own);
 if(own.length===0)segments.push({zone,panel:0,items:[],first:true,comingSoon:true});
 for(let i=0;i<own.length;i+=9){segments.push({zone,panel:i/9,items:own.slice(i,i+9),first:i===0})}
}
const lastPlayable=nodes.filter(x=>!x.planned).at(-1).number;
const byNumber=new Map(nodes.map(x=>[x.number,x]));
const defaultState=()=>({completed:[],cleared:[],xp:0,coins:0,hearts:3,heartsAt:Date.now(),day:'',newToday:0,dailyBonusDay:'',mute:true,bossDrafts:{html:'',css:'',js:''},project:{html:'',css:'',js:''},evolution:0});
let state=defaultState();try{const v=JSON.parse(localStorage.getItem(KEY));if(v&&typeof v==='object')state={...state,...v}}catch(_){/* user may disable storage */}
let chosenPet='pixel-pup';try{const v=localStorage.getItem(PET_KEY);if(PET_NAMES[v])chosenPet=v;}catch(_){}
const petAsset='assets/pet-'+chosenPet+'.png';
let activeNum=1,scrollPort,mapWorld,toastTimer,screen='map',returnAfterCelebration=false,lastViewport=0,transitionFromNum=null;
const PREFKEY='code-life-v2:preferences';let prefs={sound:false,notifyDaily:false,notifyHearts:false,notifyStreak:false,reduceMotion:matchMedia('(prefers-reduced-motion:reduce)').matches,textSize:'medium'};try{prefs={...prefs,...JSON.parse(localStorage.getItem(PREFKEY)||'{}')}}catch(_){};
function savePrefs(){try{localStorage.setItem(PREFKEY,JSON.stringify(prefs))}catch(_){flash('Settings could not be saved on this device.')}}
function isReduced(){return !!prefs.reduceMotion}
function safeBeep(){if(!prefs.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;let a=new C(),o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=660;g.gain.setValueAtTime(.0001,a.currentTime);g.gain.exponentialRampToValueAtTime(.045,a.currentTime+.015);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+.13);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.14);o.onended=()=>a.close()}catch(_){}}
function storage(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(_){flash('Progress could not be saved. Check browser storage.')}}
function localDay(){const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function syncHearts(){let t=Date.now();if(!Number.isFinite(state.heartsAt))state.heartsAt=t; if(state.hearts<3){const elapsed=Math.floor((t-state.heartsAt)/1200000);if(elapsed>0){state.hearts=Math.min(3,state.hearts+elapsed);state.heartsAt+=elapsed*1200000;if(state.hearts>=3)state.heartsAt=t;}}else state.heartsAt=t;}
function current(){const done=new Set([...state.completed,...state.cleared]);return nodes.find(x=>!done.has(x.number))?.number||nodes.at(-1).number}
function canVisit(node){return state.completed.includes(node.number)||state.cleared.includes(node.number)||node.number===activeNum}
function checkDay(){let now=localDay();if(state.day!==now){state.day=now;state.newToday=0}syncHearts();storage()}
function savePet(){try{const p=localStorage.getItem(PET_KEY);if(PET_NAMES[p])chosenPet=p}catch(_){}}
function hud(){syncHearts();return `<header class="city-topbar"><div class="city-brand">Code<span class="city-life">Life</span></div><div class="city-hud-stat" aria-label="Blue hearts"><span class="big heart" aria-hidden="true">♥</span><span id="city-heart-count">${state.hearts}</span><button class="city-plus" type="button" data-bonus="heart" aria-label="How to refill hearts">+</button></div><div class="city-hud-stat" aria-label="Experience points"><span class="big star" aria-hidden="true">★</span><small>XP</small><span id="city-xp-count">${state.xp.toLocaleString()}</span></div><div class="city-hud-stat" aria-label="Code Coins"><span class="city-gold-coin" aria-hidden="true">&lt;/&gt;</span><span id="city-coin-count">${state.coins.toLocaleString()}</span><button class="city-plus" type="button" data-bonus="coins" aria-label="How to earn Code Coins">+</button></div><button class="city-settings" id="city-settings" type="button" aria-label="Open settings" aria-expanded="false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M10.5 2h3l.7 2.7 2.2.9 2.5-1.3 2.1 2.1-1.3 2.5.9 2.2L23 11.5v3l-2.7.7-.9 2.2 1.3 2.5-2.1 2.1-2.5-1.3-2.2.9L13.5 24h-3l-.7-2.7-2.2-.9-2.5 1.3L3 19.6l1.3-2.5-.9-2.2L.7 14.5v-3l2.7-.7.9-2.2L3 6.1 5.1 4l2.5 1.3 2.2-.9z" transform="translate(1 -1) scale(.92)"/><circle cx="12" cy="12" r="3.2"/></svg></button></header>`}
const icons={lessons:'<svg viewBox="0 0 28 28" fill="none" stroke="currentColor" stroke-width="2.2"><path d="M14 6Q8 2 3 5v17q6-2 11 2 5-4 11-2V5q-5-3-11 1v18"/></svg>',courses:'<svg viewBox="0 0 28 28" fill="none" stroke="currentColor" stroke-width="2.1"><path d="m2 10 12-6 12 6-12 6L2 10Zm4 4v6q8 5 16 0v-6"/></svg>',playground:'<svg viewBox="0 0 28 28" fill="none" stroke="currentColor" stroke-width="2"><path d="M7 8h14a5 5 0 0 1 5 5l1 7q-1 6-6 1l-3-3h-8l-3 3q-5 5-6-1l1-7a5 5 0 0 1 5-5ZM8 11v8m-4-4h8m8-2h1m2 3h1"/></svg>',progress:'<svg viewBox="0 0 28 28" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><path d="M5 23v-8m7 8V5m7 18V11m6 12v-5"/></svg>',pet:'<svg viewBox="0 0 28 28" fill="none" stroke="currentColor" stroke-width="2"><path d="m5 13-1-9 7 4a12 12 0 0 1 6 0l7-4-1 9a10 10 0 1 1-18 0ZM10 15h.1m8 0h.1M12 19q2 2 4 0"/></svg>'};
function nav(){return `<nav class="city-bottom-nav" aria-label="Main navigation">${[['lessons','Lessons'],['courses','Courses'],['playground','Playground'],['progress','Progress'],['pet','My Pet']].map(([key,label])=>`<button type="button" class="city-nav-btn ${key==='lessons'?'active':''}" data-tab="${key}" ${key==='lessons'?'aria-current="page"':''}><span class="symbol">${icons[key]}</span><span>${label}</span></button>`).join('')}</nav>`}
function flash(message){let toast=root.querySelector('.city-toast');if(!toast){toast=document.createElement('div');toast.className='city-toast';toast.setAttribute('role','status');root.querySelector('.city-shell')?.appendChild(toast);}toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toast.hidden=true},3200)}
function progressPadClass(item){if(state.completed.includes(item.number))return 'is-complete';if(state.cleared.includes(item.number))return 'is-cleared';if(item.number===activeNum)return 'is-current';return 'is-locked'}
function drawPanel(segment){
 const {zone,items,first}=segment;
 const wave=[.51,.67,.72,.56,.44,.47,.67,.64,.52];const positions=items.map((_,i)=>({x:wave[i%9],y:.88-i*.095}));
 let controls=items.map((node,i)=>{
  const pos=positions[i],cls=progressPadClass(node),complete=state.completed.includes(node.number),currentNode=node.number===activeNum;
  const label=node.kind==='boss'?'Boss Build checkpoint':node.lesson.title;
  return `<button class="city-pad ${cls} ${node.kind==='boss'?'is-boss':''}" type="button" data-level="${node.number}" aria-label="Level ${node.number}. ${escapeText(label)}. ${cls.replace('is-','')}" style="left:${pos.x*100}%;top:${pos.y*100}%"><span>${node.number}</span>${node.kind==='boss'?'<span class="boss-diamond" aria-hidden="true">✦</span>':''}${complete?'<span class="check" aria-hidden="true">✓</span>':''}${currentNode?`<img class="city-active-pet ${state.evolution?'is-evolved':''}" src="./pet-map-${chosenPet}.png" alt="${PET_NAMES[chosenPet]} hovering over current level" loading="lazy">`:''}</button>`}).join('');
 const sign=first?`<div class="city-road-sign" style="--accent:${zone.accent}" aria-label="${zone.sign} ${zone.name}"><small>${zone.sign}</small>${zone.name.toUpperCase()}${segment.comingSoon?'<small style="margin-top:6px;font-size:11px">MORE LESSONS TO COME</small>':''}</div>`:'';
 return `<section class="city-panel ${zone.id}" data-zone="${zone.id}" aria-label="${zone.name}" style="--accent:${zone.accent}">${sign}${controls}</section>`;
}
function escapeText(str){return String(str).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}

// Distinctive landmarks rather than repeated tinted copies of the same photo.
function drawScenery(segment){
 const id=segment.zone.id;
 const landmarks={
 html:`<g class="sc-glow"><ellipse cx="64" cy="472" rx="94" ry="32" fill="#b7f4ff" opacity=".76"/><path d="M0 459Q61 431 129 454L109 485 53 510 0 479Z" fill="#507cbd" stroke="#b7ffff" stroke-width="5"/><g fill="#ebffff" stroke="#27aaff" stroke-width="4"><rect x="4" y="325" width="78" height="124" rx="22"/><rect x="18" y="292" width="55" height="40" rx="17"/><rect x="9" y="345" width="27" height="53" rx="12"/></g><path d="M12 334v-20q28-34 65 0v20" fill="none" stroke="#00d7ff" stroke-width="8"/><g fill="#46faac"><circle cx="21" cy="318" r="13"/><circle cx="89" cy="361" r="20"/><circle cx="57" cy="453" r="11"/></g><g stroke="#b2faff" stroke-width="5" fill="#eefaff"><path d="M295 166V78h43v88z"/><path d="M343 192V54h35v138z"/></g><path d="M291 168L386 168" stroke="#04caff" stroke-width="7"/></g>`,
 css:`<g class="sc-glow"><path d="M0 425L125 407 112 445 34 475Z" fill="#5c5bc4" stroke="#b7a0ff" stroke-width="5"/><g fill="#292f80" stroke="#b66cff" stroke-width="6"><path d="M3 403V238Q60 170 120 238V403Z"/><path d="M291 370V210Q328 150 390 216V370Z"/></g><path d="M26 270Q65 211 102 270M312 242Q345 193 375 239" fill="none" stroke="#f6a3ff" stroke-width="9"/><g fill="none" stroke-width="7"><ellipse cx="63" cy="226" rx="49" ry="10" stroke="#9ffbff"/><ellipse cx="339" cy="203" rx="43" ry="11" stroke="#ff9be8"/></g><g fill="#dfafff"><circle cx="32" cy="410" r="17"/><circle cx="93" cy="413" r="13"/><circle cx="352" cy="377" r="18"/></g><g stroke="#c3f9ff" stroke-width="3"><path d="M9 306h105M302 297h85"/></g></g>`,
 js:`<g class="sc-glow"><path d="M0 418L136 400 115 450 35 478Z" fill="#5b72ba" stroke="#ffc75c" stroke-width="4"/><g fill="#093779" stroke="#ffb938" stroke-width="5"><path d="M5 390V171h38v219z"/><path d="M48 394V105h37v289z"/><path d="M91 394V202h39v192z"/><path d="M290 375V166h31v209z"/><path d="M327 375V92h41v283z"/><path d="M370 375V216h25v159z"/></g><g stroke="#ffe39d" stroke-width="3" opacity=".9"><path d="M16 211h14M16 244h14M58 140h16M58 174h16M58 208h16M58 242h16M101 236h16M337 130h20M337 166h20M337 202h20M337 238h20M298 210h12"/></g><path d="M9 184Q135 91 330 150" fill="none" stroke="#fbe777" stroke-width="6" stroke-dasharray="2 11"/><circle cx="349" cy="89" r="19" fill="none" stroke="#ffe88c" stroke-width="6"/></g>`,
 python:`<g class="sc-glow"><ellipse cx="62" cy="453" rx="96" ry="25" fill="#43f5dc" opacity=".6"/><path d="M0 445L138 422 105 481 29 490Z" fill="#236c96" stroke="#5ffff0" stroke-width="4"/><g fill="#0a6580" stroke="#70ffed" stroke-width="4"><rect x="9" y="293" width="100" height="137" rx="13"/><rect x="31" y="268" width="59" height="32" rx="14"/><rect x="294" y="260" width="86" height="133" rx="9"/><rect x="308" y="229" width="55" height="35" rx="12"/></g><g fill="#e5fffb"><rect x="21" y="322" width="72" height="25" rx="5"/><rect x="307" y="290" width="58" height="21" rx="5"/></g><g fill="none" stroke-width="4" stroke="#acffea"><path d="M25 372q55-59 68 0t-68 0t68 0"/><circle cx="336" cy="351" r="20"/><path d="M332 332v39m-14-19h37"/></g><path d="M307 213q25-60 56 0" fill="none" stroke="#13f8df" stroke-width="8"/></g>`,
 sql:`<g class="sc-glow"><path d="M0 460L143 439 102 488 0 482Z" fill="#0d3272" stroke="#98c5ff" stroke-width="4"/><g fill="#071b3a" stroke="#66b9ff" stroke-width="5"><path d="M0 235L87 202 139 240V432L80 466 0 430Z"/><path d="M263 246L345 194 390 222V435L337 461 265 425Z"/></g><path d="M23 279h66v119H23zM292 275h78v121h-78z" fill="#001a3d" stroke="#3dcaff" stroke-width="5"/><g stroke="#8eeeff" stroke-width="3"><path d="M32 300h50M32 320h50M32 340h50M32 360h50M32 380h50M301 300h60M301 320h60M301 340h60M301 360h60M301 380h60"/></g><g fill="#2ff7df"><circle cx="42" cy="300" r="4"/><circle cx="311" cy="320" r="4"/><circle cx="54" cy="380" r="4"/></g><path d="M282 117l41-24 40 24v50l-40 22-41-22Z" fill="#0f3c8c" stroke="#b1e2ff" stroke-width="5"/><path d="M307 133l16 16 21-26" fill="none" stroke="#65ffdb" stroke-width="7"/></g>`
 };
 return `<div class="city-zone-art ${id}" aria-hidden="true"><svg class="city-landmark-art" viewBox="0 0 390 700" preserveAspectRatio="xMidYMid slice" role="presentation">${landmarks[id]}</svg></div>`;
}
function smoothRoad(points){if(points.length<2)return '';let d=`M${points[0][0]},${points[0][1]}`;for(let i=0;i<points.length-1;i++){let a=points[Math.max(0,i-1)],b=points[i],c=points[i+1],z=points[Math.min(points.length-1,i+2)];let t=.27;d+=` C${(b[0]+(c[0]-a[0])*t).toFixed(1)},${(b[1]+(c[1]-a[1])*t).toFixed(1)} ${(c[0]-(z[0]-b[0])*t).toFixed(1)},${(c[1]-(z[1]-b[1])*t).toFixed(1)} ${c[0]},${c[1]}`;}return d;}
function drawContinuousRoad(){
 if(!mapWorld||!root.contains(mapWorld))return;
 const svg=mapWorld.querySelector('.city-road-svg');if(!svg)return;
 const wr=mapWorld.getBoundingClientRect(),w=wr.width,h=wr.height;
 let pts=[...mapWorld.querySelectorAll('.city-pad')].map(b=>{let r=b.getBoundingClientRect();return [Math.round(r.left-wr.left+r.width/2),Math.round(r.top-wr.top+r.height/2)]});
 // The planned towns also have a visible highway, but no fake clickable lesson pads.
 for(const zone of ['python','sql']){const el=mapWorld.querySelector(`.city-panel.${zone}`);if(!el)continue;const y=el.getBoundingClientRect().top-wr.top;const sh=el.getBoundingClientRect().height;for(const [x,p] of [[.53,.08],[.65,.27],[.48,.5],[.69,.69],[.51,.90]])pts.push([Math.round(w*x),Math.round(y+sh*p)]);}
 // Join all districts with the same SVG road. There are no separately cropped or repeated road images.
 pts.sort((a,b)=>a[1]-b[1]);for(let i=0;i<pts.length-1;i++)if(pts[i+1][1]-pts[i][1]>100){const a=pts[i],b=pts[i+1];pts.splice(++i,0,[Math.round((a[0]+b[0])/2),Math.round((a[1]+b[1])/2)]);}
 let d=smoothRoad(pts);svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.innerHTML=`<defs><filter id="city-road-shadow" x="-30%" y="-25%" width="160%" height="160%"><feDropShadow dx="0" dy="9" stdDeviation="7" flood-color="#003776" flood-opacity=".58"/></filter><linearGradient id="city-road-fill" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#073f92"/><stop offset=".23" stop-color="#1a87e6"/><stop offset=".52" stop-color="#3aa9f6"/><stop offset=".82" stop-color="#1679dd"/><stop offset="1" stop-color="#07488f"/></linearGradient></defs><path d="${d}" stroke="#03549e" stroke-width="93" fill="none" filter="url(#city-road-shadow)" stroke-linecap="round" stroke-linejoin="round"/><path d="${d}" stroke="#e1fbff" stroke-width="89" fill="none" stroke-linecap="round" stroke-linejoin="round"/><path d="${d}" stroke="url(#city-road-fill)" stroke-width="83" fill="none" stroke-linecap="round" stroke-linejoin="round"/><path d="${d}" stroke="#82efff" stroke-opacity=".75" stroke-width="1.8" stroke-dasharray="10 25" fill="none"/><path d="${d}" stroke="#e2ffff" stroke-width="2" stroke-dasharray="7 23" fill="none" opacity=".72"/>`;
}
function settingSheet(){return `<div class="city-settings-backdrop" id="city-settings-backdrop" hidden></div><aside class="city-settings-drawer" id="city-settings-drawer" role="dialog" aria-modal="true" aria-labelledby="city-settings-title" aria-hidden="true"><div class="city-drawer-header"><h2 id="city-settings-title">Settings</h2><button type="button" class="city-drawer-close" id="city-close-settings" aria-label="Close settings">✕</button></div><div class="city-drawer-scroll"><section><h3>Experience</h3><label class="city-toggle"><span>Sound effects</span><input type="checkbox" data-setting="sound" ${prefs.sound?'checked':''}></label><label class="city-toggle"><span>Reduce Motion</span><input type="checkbox" data-setting="reduceMotion" ${prefs.reduceMotion?'checked':''}></label></section><section><h3>Notifications</h3><p class="city-settings-note">Choose your reminders. Background phone alerts will become available when push notifications are connected.</p><label class="city-toggle"><span>Daily learning reminders</span><input type="checkbox" data-setting="notifyDaily" ${prefs.notifyDaily?'checked':''}></label><label class="city-toggle"><span>Heart refill reminders</span><input type="checkbox" data-setting="notifyHearts" ${prefs.notifyHearts?'checked':''}></label><label class="city-toggle"><span>Streak warnings</span><input type="checkbox" data-setting="notifyStreak" ${prefs.notifyStreak?'checked':''}></label></section><section><h3>Learning preferences</h3><label for="city-text-size">Lesson text size</label><select id="city-text-size" class="city-size-select"><option value="small" ${prefs.textSize==='small'?'selected':''}>Small</option><option value="medium" ${prefs.textSize==='medium'?'selected':''}>Medium</option><option value="large" ${prefs.textSize==='large'?'selected':''}>Large</option></select></section><section class="city-danger-area"><h3>Your progress</h3><button type="button" id="city-reset-progress" class="city-reset-btn">Reset Progress</button><p class="city-settings-note">This permanently resets your saved lessons, hearts, coins and projects on this device.</p></section></div></aside>`;}
function bindSettings(){const shell=root.querySelector('.city-shell');if(!shell)return;shell.insertAdjacentHTML('beforeend',settingSheet());const curtain=root.querySelector('#city-settings-backdrop'),drawer=root.querySelector('#city-settings-drawer'),gear=root.querySelector('#city-settings');let previousFocus=null;function close(){drawer.classList.remove('open');curtain.hidden=true;drawer.setAttribute('aria-hidden','true');gear?.setAttribute('aria-expanded','false');previousFocus?.focus()};function open(){previousFocus=document.activeElement;curtain.hidden=false;drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');gear?.setAttribute('aria-expanded','true');root.querySelector('#city-close-settings').focus()};gear?.addEventListener('click',open);curtain.addEventListener('click',close);root.querySelector('#city-close-settings').addEventListener('click',close);drawer.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const els=[...drawer.querySelectorAll('button,input,select')].filter(x=>!x.disabled),a=els[0],b=els.at(-1);if(e.shiftKey&&document.activeElement===a){e.preventDefault();b.focus()}else if(!e.shiftKey&&document.activeElement===b){e.preventDefault();a.focus()}}});drawer.querySelectorAll('[data-setting]').forEach(inp=>inp.addEventListener('change',()=>{prefs[inp.dataset.setting]=inp.checked;savePrefs();root.classList.toggle('city-reduce-motion',isReduced());if(inp.dataset.setting==='sound'&&inp.checked)safeBeep()}));drawer.querySelector('#city-text-size').addEventListener('change',e=>{prefs.textSize=e.target.value;savePrefs();root.dataset.textSize=prefs.textSize});drawer.querySelector('#city-reset-progress').addEventListener('click',()=>{if(!confirm('Reset all Code City progress and project drafts on this device? This cannot be undone.'))return;state=defaultState();storage();lastViewport=0;close();location.hash='/city';assembleMap();flash('Your Code City progress has been reset.')});}
function assembleMap(){savePet();checkDay();activeNum=current();const ordered=[...segments].reverse(),panels=ordered.map(drawPanel).join(''),scenery=ordered.map(drawScenery).join('');root.innerHTML=`<div class="city-shell">${hud()}<div class="city-scroll" id="city-scroll"><div class="city-world"><div class="city-world-backdrops" aria-hidden="true">${scenery}</div><svg class="city-road-svg" aria-hidden="true"></svg><div class="city-world-panels">${panels}</div></div></div><button class="city-return" type="button" id="city-return">⌖ &nbsp;Return to My Level</button>${nav()}</div>`;scrollPort=root.querySelector('#city-scroll');mapWorld=root.querySelector('.city-world');root.classList.toggle('city-reduce-motion',isReduced());root.dataset.textSize=prefs.textSize;screen='map';bindCommon();bindMap();requestAnimationFrame(drawContinuousRoad);
 requestAnimationFrame(()=>{if(returnAfterCelebration){if(transitionFromNum!==null)animatePetToNext(transitionFromNum,activeNum);else scrollToCurrent(true);transitionFromNum=null;returnAfterCelebration=false}else if(lastViewport>0){scrollPort.scrollTop=lastViewport;updateReturn()}else scrollToCurrent(false)});
}
function scrollToCurrent(smooth){const pad=root.querySelector(`.city-pad[data-level="${activeNum}"]`);if(!pad||!scrollPort)return;let top=pad.getBoundingClientRect().top-scrollPort.getBoundingClientRect().top+scrollPort.scrollTop-scrollPort.clientHeight*.52;scrollPort.scrollTo({top:Math.max(0,top),behavior:smooth&&!isReduced()?'instant':'smooth'});}
function animatePetToNext(fromNum,toNum){
 const from=root.querySelector(`.city-pad[data-level="${fromNum}"]`),to=root.querySelector(`.city-pad[data-level="${toNum}"]`);
 if(!from||!to||from===to||isReduced()){scrollToCurrent(false);return;}
 // Show the previous pad in place; the chosen pet itself glides above the road as
 // the camera follows toward the next pad. The artwork never changes identity.
 const oldTop=from.getBoundingClientRect().top-scrollPort.getBoundingClientRect().top+scrollPort.scrollTop-scrollPort.clientHeight*.57;
 scrollPort.scrollTop=Math.max(0,oldTop);
 const target=to.querySelector('.city-active-pet');if(target)target.style.visibility='hidden';
 const ghost=document.createElement('img');ghost.className='city-floating-pet';ghost.alt='';ghost.src='./pet-map-'+chosenPet+'.png';ghost.style.transition='none';root.querySelector('.city-shell').appendChild(ghost);
 let start=from.getBoundingClientRect(),startX=start.left+start.width/2-55,startY=start.top-113,begin=performance.now();
 scrollToCurrent(true);
 function frame(t){const duration=1150,p=Math.min(1,(t-begin)/duration),e=p*p*(3-2*p),dest=to.getBoundingClientRect();
  // Destination changes every frame while the user-view scroll animates.
  ghost.style.left=(startX+(dest.left+dest.width/2-55-startX)*e)+'px';
  ghost.style.top=(startY+(dest.top-113-startY)*e-11*Math.sin(p*Math.PI))+'px';
  if(p<1)requestAnimationFrame(frame);else{ghost.remove();if(target)target.style.visibility='visible';updateReturn()}
 }
 requestAnimationFrame(frame);
}
function updateReturn(){const pad=root.querySelector(`.city-pad[data-level="${activeNum}"]`);const rb=root.querySelector('#city-return');if(!pad||!rb||!scrollPort)return;const a=pad.getBoundingClientRect(),b=scrollPort.getBoundingClientRect();rb.classList.toggle('show',a.top<b.top+30||a.top>b.bottom-35)}
function bindCommon(){bindSettings();root.querySelectorAll('[data-bonus]').forEach(b=>b.addEventListener('click',()=>flash(b.dataset.bonus==='heart'?'Earn blue hearts through reviews or wait 20 minutes per heart.':'Earn Code Coins by completing lessons and Boss Builds.')));root.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='lessons'){if(location.hash!=='#/city')location.hash='/city';else scrollToCurrent(true)}else flash('We’ll build this screen from your approved screenshot next.');}));}
function bindMap(){root.querySelectorAll('[data-level]').forEach(p=>p.addEventListener('click',()=>{const id=Number(p.dataset.level),node=byNumber.get(id);if(node.planned){flash('This town’s lessons are being developed.');return;}if(canVisit(node)){lastViewport=scrollPort.scrollTop;location.hash='/lesson/'+id;}else{let prior=byNumber.get(activeNum);flash(`${PET_NAMES[chosenPet]}: Complete Level ${activeNum} first!`);}}));root.querySelector('#city-return').addEventListener('click',()=>scrollToCurrent(true));scrollPort.addEventListener('scroll',updateReturn,{passive:true});}
function showProgress(){screen='progress';const zoneCards=ZONES.map(z=>{const all=nodes.filter(n=>n.zone.id===z.id),count=all.filter(n=>state.completed.includes(n.number)||state.cleared.includes(n.number)).length;return `<div class="city-lesson-card"><strong>${z.name}</strong><p>${count} of ${all.length} levels reached</p><progress max="${all.length}" value="${count}" style="width:100%;accent-color:#30ddfa"></progress></div>`}).join('');root.innerHTML=`<div class="city-shell">${hud()}<div class="city-scene" style="position:relative;inset:auto;flex:1"><button class="city-secondary" id="city-back">← Code City</button><h1>Progress</h1><div class="city-lesson-card"><b>★ ${state.xp} XP</b> &nbsp; 🪙 ${state.coins} Coins</div>${zoneCards}</div>${nav()}</div>`;bindCommon();root.querySelector('#city-back').onclick=()=>location.hash='/city';}
function takeHeart(){syncHearts();if(state.hearts>=3)state.heartsAt=Date.now();state.hearts=Math.max(0,state.hearts-1);storage();let e=root.querySelector('#city-heart-count');if(e)e.textContent=String(state.hearts);}
function showReview(){const lessons=bodyData.lessons.filter(l=>state.completed.some(n=>byNumber.get(n)?.lesson?.id===l.id));const lesson=lessons.at(-1);if(!lesson){flash('Hearts return automatically, one every 20 minutes.');return;}const question=lesson.quiz[0];if(!question){flash('One heart returns every 20 minutes.');return;}root.querySelector('#city-lesson-content').innerHTML=`<div class="city-lesson-card"><h2>Quick Review 💙</h2><p>${escapeText(question.q)}</p>${question.options.map((o,i)=>`<button type="button" class="city-quiz-option" data-review-answer="${i}">${escapeText(o)}</button>`).join('')}<p>Complete this review to restore one heart.</p></div>`;root.querySelectorAll('[data-review-answer]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.reviewAnswer)===question.answer){state.hearts=Math.min(3,state.hearts+1);state.heartsAt=Date.now();storage();flash('Great review! +1 blue heart.');showLesson(byNumber.get(Number(location.hash.split('/').at(-1))))}else flash(`${PET_NAMES[chosenPet]}: Not quite—think about the lesson and try again.`)});}
function showLesson(node){if(!node||node.planned){location.hash='/city';return;}screen='lesson';root.classList.toggle('city-reduce-motion',isReduced());root.dataset.textSize=prefs.textSize;let lesson=node.lesson||null,boss=node.kind==='boss';root.innerHTML=`<div class="city-shell">${hud()}<div class="city-scene" style="position:relative;inset:auto;flex:1"><button type="button" id="city-back" class="city-secondary">← Code City</button><div id="city-lesson-content"></div></div>${nav()}</div>`;bindCommon();root.querySelector('#city-back').onclick=()=>location.hash='/city';if(boss)showBoss(node);else showLessonStages(node);}
function showLessonStages(node){const lesson=node.lesson;let stage=0, code=lesson.starter||'',responses=[],quizIndex=0;const el=root.querySelector('#city-lesson-content');
function base(){return `<div class="city-breadcrumb">${node.zone.name} &nbsp;→&nbsp; Level ${node.number}</div><h1 class="city-lesson-heading">${escapeText(lesson.title)}</h1><div style="margin:8px 0 12px"><span class="city-step-dot ${stage===0?'active':''}">1</span><span class="city-step-dot ${stage===1?'active':''}">2</span><span class="city-step-dot ${stage===2?'active':''}">3</span></div>`}
function intro(){stage=0;el.innerHTML=base()+`<div class="city-lesson-card"><img class="city-lesson-pet" src="./pet-map-${chosenPet}.png" alt="${PET_NAMES[chosenPet]}"><h2>Let’s learn!</h2><p>${escapeText(lesson.concept)}</p>${lesson.steps.map(t=>`<p>✦ ${escapeText(t)}</p>`).join('')}<div class="city-preview"><code>${escapeText(lesson.example)}</code></div></div><button class="city-primary" id="lesson-next">Your turn →</button>`;el.querySelector('#lesson-next').onclick=practice;}
function practice(){stage=1;el.innerHTML=base()+`<div class="city-lesson-card"><img class="city-lesson-pet" src="./pet-map-${chosenPet}.png" alt=""><h2>Your turn!</h2><p>${escapeText(lesson.task)}</p><textarea class="city-code-editor" id="lesson-code" spellcheck="false" aria-label="Write your code">${escapeText(code)}</textarea><div style="display:flex;flex-wrap:wrap;gap:6px;margin:10px 0">${['<','>','/','=','"','(',')','{','}',';'].map(t=>`<button class="city-secondary" style="padding:6px 11px" data-symbol="${escapeText(t)}">${escapeText(t)}</button>`).join('')}</div><p class="city-error" id="lesson-hint" aria-live="polite"></p><button class="city-secondary" id="lesson-help">Hint</button> <button class="city-primary" id="lesson-check">Check →</button></div>`;
const txt=el.querySelector('#lesson-code');el.querySelectorAll('[data-symbol]').forEach(b=>b.onclick=()=>{let s=txt.selectionStart,e=txt.selectionEnd,symbol=b.dataset.symbol;txt.value=txt.value.slice(0,s)+symbol+txt.value.slice(e);txt.focus();txt.setSelectionRange(s+symbol.length,s+symbol.length)});
let hint=0;el.querySelector('#lesson-help').onclick=()=>{el.querySelector('#lesson-hint').textContent=lesson.hints[Math.min(hint++,lesson.hints.length-1)]};
el.querySelector('#lesson-check').onclick=()=>{code=txt.value;const rules=lesson.rules||[];let invalid;for(const r of rules){try{if(!new RegExp(r.value,'im').test(code)){invalid=r.message;break}}catch(_){invalid='Check your syntax and try again.';break}}if(invalid){takeHeart();el.querySelector('#lesson-hint').textContent=state.hearts===0?'Out of hearts! Complete a review or wait for a refill.':`${PET_NAMES[chosenPet]}: ${lesson.hints[Math.min(hint++,lesson.hints.length-1)]||invalid}`;if(state.hearts===0){el.querySelector('#lesson-check').disabled=true;let rev=document.createElement('button');rev.className='city-primary';rev.textContent='Quick Review to earn a heart';rev.onclick=showReview;el.querySelector('.city-lesson-card').appendChild(rev)}return;}quiz();};}
function quiz(){stage=2;if(state.hearts===0){showReview();return;}const q=lesson.quiz[quizIndex];if(!q){const passed=responses.filter(x=>x).length/Math.max(1,responses.length)>=.8;if(passed)completeLevel(node);else{flash('Review the lesson and retake the quiz.');quizIndex=0;responses=[];intro()}return;}let answer=null;el.innerHTML=base()+`<div class="city-lesson-card"><img class="city-lesson-pet" src="./pet-map-${chosenPet}.png" alt=""><h2>Quick Quiz</h2><p>Question ${quizIndex+1} of ${lesson.quiz.length}</p><h3>${escapeText(q.q)}</h3>${q.options.map((v,i)=>`<button type="button" class="city-quiz-option" data-answer="${i}">${escapeText(v)}</button>`).join('')}<p class="city-error" id="quiz-hint" aria-live="polite"></p><button class="city-primary" id="quiz-next">Check answer</button></div>`;
el.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{answer=Number(b.dataset.answer);el.querySelectorAll('[data-answer]').forEach(o=>o.classList.toggle('selected',o===b))});
el.querySelector('#quiz-next').onclick=()=>{if(answer===null){el.querySelector('#quiz-hint').textContent='Choose an answer first.';return;}if(answer!==q.answer){takeHeart();el.querySelector('#quiz-hint').textContent=`${PET_NAMES[chosenPet]}: Here’s a hint—think back to the example! Try again.`;if(state.hearts===0){el.querySelector('#quiz-next').disabled=true;const b=document.createElement('button');b.className='city-primary';b.textContent='Quick Review';b.onclick=showReview;el.querySelector('.city-lesson-card').appendChild(b)}return;}responses.push(true);quizIndex++;quiz();};}
intro();}
function showBoss(node){const track=node.zone.id;if(!['html','css','js'].includes(track)){flash('This Boss Build is still in development.');return;}let drafts=state.bossDrafts,project=state.project;let hint=track==='html'?'Create your website using a heading, paragraph, and button.':track==='css'?'Style the same website with a body rule and at least one color or layout rule.':'Make the website interactive using addEventListener.';let defaultCode=track==='html'?project.html||'<!doctype html>\n<html>\n<body>\n  <h1>My website</h1>\n  <p>Welcome!</p>\n  <button>Click me</button>\n</body>\n</html>':track==='css'?project.css||'body {\n  background: #dff6ff;\n  color: #12345c;\n}\nbutton { padding: 12px; }':project.js||'document.querySelector("button").addEventListener("click", () => {\n  alert("Hello!");\n});';
const el=root.querySelector('#city-lesson-content');el.innerHTML=`<div class="city-breadcrumb">${node.zone.name} • Boss Build</div><h1 class="city-lesson-heading">Build your growing website ✨</h1><div class="city-lesson-card"><p>${hint}</p><p>Your code will be saved and used again in the next town.</p><textarea class="city-code-editor" id="boss-code" style="min-height:240px" spellcheck="false">${escapeText(drafts[track]||defaultCode)}</textarea><p id="boss-status" style="color:#8feaff">Saved locally on this device.</p><div style="display:flex;gap:9px;flex-wrap:wrap"><button class="city-secondary" id="boss-save">Save draft</button><button class="city-primary" id="boss-check">Finish Boss Build →</button></div><p class="city-error" id="boss-hint"></p></div>`;
const ta=el.querySelector('#boss-code'),status=el.querySelector('#boss-status');function save(){drafts[track]=ta.value;storage();status.textContent='Draft saved on this device ✓';}let deb;ta.addEventListener('input',()=>{status.textContent='Saving…';clearTimeout(deb);deb=setTimeout(save,450)});el.querySelector('#boss-save').onclick=save;el.querySelector('#boss-check').onclick=()=>{save();let valid=track==='html'?/<h1\b[^>]*>.*?<\/h1>/is.test(ta.value)&&/<p\b[^>]*>.*?<\/p>/is.test(ta.value)&&/<button\b/is.test(ta.value):track==='css'?/body\s*\{[^}]+\}/is.test(ta.value)&&/[\w-]+\s*:\s*[^;}{]+/i.test(ta.value):/addEventListener\s*\(/.test(ta.value);if(!valid){el.querySelector('#boss-hint').textContent=`${PET_NAMES[chosenPet]}: ${hint}`;return;}project[track]=ta.value;storage();completeLevel(node);};}
function completeLevel(node){if(state.completed.includes(node.number)){location.hash='/city';return;}const boss=node.kind==='boss';state.completed.push(node.number);state.xp+=boss?160:40;state.coins+=boss?60:8;if(boss){state.evolution=ZONES.findIndex(z=>z.id===node.zone.id)+1;}else{checkDay();state.newToday++;if(state.newToday===4&&state.dailyBonusDay!==state.day){state.dailyBonusDay=state.day;state.xp+=60;state.coins+=20;}}storage();const next=nodes.find(x=>!state.completed.includes(x.number)&&!state.cleared.includes(x.number));activeNum=next?.number||node.number;transitionFromNum=node.number;
root.querySelector('.city-shell')?.insertAdjacentHTML('beforeend',`<div class="city-celebrate" id="city-celebrate"><h1>${boss?'TOWN COMPLETE! 🎉':'LEVEL COMPLETE! ✨'}</h1><img src="./pet-map-${chosenPet}.png" alt="${PET_NAMES[chosenPet]} celebrates"><p>${escapeText(node.zone.name)} • Level ${node.number}</p><h2>+${boss?160:40} XP &nbsp; +${boss?60:8} Coins</h2>${boss?'<p>Town complete! Your pet evolves and your next town unlocks.</p>':''}<p style="color:#b5f4ff">Returning to Code City…</p></div>`);
setTimeout(()=>{returnAfterCelebration=true;lastViewport=0;location.hash='/city';if(location.hash==='#/city')assembleMap()},boss?3300:2200);
}
function route(){const h=location.hash;if(h==='#/city'){assembleMap()}else if(h.startsWith('#/lesson/')){const number=Number(h.split('/').at(-1)),node=byNumber.get(number);if(!node||node.planned||!canVisit(node)){location.hash='/city';return;}checkDay();if(!state.completed.includes(number)&&node.kind==='lesson'&&state.newToday>=4){assembleMap();flash('Four new lessons today! Review or do an unlocked Boss Build.');return;}showLesson(node)} }
root.addEventListener('click',e=>{ /* non-interactive background intentionally ignores all taps */ });
window.CodeCity={route,show:route,goToCurrent:()=>scrollToCurrent(true),getState:()=>structuredClone(state),getNodes:()=>nodes.map(x=>({number:x.number,zone:x.zone.id,kind:x.kind,planned:x.planned}))};
addEventListener('hashchange',()=>{if(location.hash==='#/city'||location.hash.startsWith('#/lesson/'))route()});addEventListener('resize',()=>{if(screen==='map'&&mapWorld)requestAnimationFrame(drawContinuousRoad)},{passive:true});
if(location.hash==='#/city'||location.hash.startsWith('#/lesson/'))route();
})();