/* Code Life v2 — Code City map build. No scenery animation, no invented extra pets.
   Original local-only game state. HTML/CSS/JS lessons sourced from existing curriculum.js;
   Python/SQL road sections are visually planned, NOT falsely represented as ready lessons. */
(()=>{'use strict';
const root=document.querySelector('#city-root');if(!root)return;
const KEY='code-life-v2:city-state';const PET_KEY='code-life-v2:onboarding:pet';
const PET_NAMES={'pixel-pup':'Pixel Pup','byte-cat':'Byte Cat','nova-owl':'Nova Owl','loop-fox':'Loop Fox','chip-bunny':'Chip Bunny','glitch-dino':'Glitch Dino'};
const ZONES=[
  {id:'html',name:'HTML Town',sign:'WELCOME TO',accent:'#64dfff'},
  {id:'css',name:'CSS District',sign:'NOW ENTERING',accent:'#c29bff'},
  {id:'js',name:'JavaScript City',sign:'WELCOME TO',accent:'#f8d978'},
  {id:'python',name:'Python Lab',sign:'NOW ENTERING',accent:'#78f5df'},
  {id:'sql',name:'Data Vault',sign:'WELCOME TO',accent:'#a3c8ff'}
];
// No made-up level counts for later towns: their detailed lesson plans are pending.
const PLANNED={python:[],sql:[]};
const bodyData=window.CODE_LIFE_DATA||{lessons:[]};
let n=0;const nodes=[],segments=[];
for(const zone of ZONES){
 const lessons=['html','css','js'].includes(zone.id)?bodyData.lessons.filter(l=>l.track===zone.id):PLANNED[zone.id].map((title,i)=>({id:zone.id+'-'+(i+1),title,track:zone.id,planned:true}));
 const own=lessons.map(lesson=>({number:++n,zone,kind:'lesson',lesson,planned:!!lesson.planned}));
 if(!PLANNED[zone.id])own.push({number:++n,zone,kind:'boss',lesson:null,planned:false});
 nodes.push(...own);
 if(own.length===0)segments.push({zone,panel:0,items:[],first:true,comingSoon:true});
 for(let i=0;i<own.length;i+=4){segments.push({zone,panel:i/4,items:own.slice(i,i+4),first:i===0})}
}
const lastPlayable=nodes.filter(x=>!x.planned).at(-1).number;
const byNumber=new Map(nodes.map(x=>[x.number,x]));
const defaultState=()=>({completed:[],cleared:[],xp:0,coins:0,hearts:3,heartsAt:Date.now(),day:'',newToday:0,dailyBonusDay:'',mute:true,bossDrafts:{html:'',css:'',js:''},project:{html:'',css:'',js:''},evolution:0});
let state=defaultState();try{const v=JSON.parse(localStorage.getItem(KEY));if(v&&typeof v==='object')state={...state,...v}}catch(_){/* user may disable storage */}
let chosenPet='pixel-pup';try{const v=localStorage.getItem(PET_KEY);if(PET_NAMES[v])chosenPet=v;}catch(_){}
const petAsset='assets/pet-'+chosenPet+'.png';
let activeNum=1,scrollPort,mapWorld,toastTimer,screen='map',returnAfterCelebration=false,lastViewport=0,transitionFromNum=null;
function storage(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(_){flash('Progress could not be saved. Check browser storage.')}}
function localDay(){const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function syncHearts(){let t=Date.now();if(!Number.isFinite(state.heartsAt))state.heartsAt=t; if(state.hearts<3){const elapsed=Math.floor((t-state.heartsAt)/1200000);if(elapsed>0){state.hearts=Math.min(3,state.hearts+elapsed);state.heartsAt+=elapsed*1200000;if(state.hearts>=3)state.heartsAt=t;}}else state.heartsAt=t;}
function current(){const done=new Set([...state.completed,...state.cleared]);return nodes.find(x=>!done.has(x.number))?.number||nodes.at(-1).number}
function canVisit(node){return state.completed.includes(node.number)||state.cleared.includes(node.number)||node.number===activeNum}
function checkDay(){let now=localDay();if(state.day!==now){state.day=now;state.newToday=0}syncHearts();storage()}
function savePet(){try{const p=localStorage.getItem(PET_KEY);if(PET_NAMES[p])chosenPet=p}catch(_){}}
function hud(){syncHearts();return `<header class="city-topbar"><div class="city-brand">Code <span class="city-life">Life</span></div><div class="city-hud-stat" aria-label="Blue hearts"><span class="big heart">♡</span><span id="city-heart-count">${state.hearts}</span><button class="city-plus" type="button" data-bonus="heart" aria-label="How to refill hearts">+</button></div><div class="city-hud-stat" aria-label="Experience points"><span class="big star">★</span><small>XP</small><span id="city-xp-count">${state.xp.toLocaleString()}</span></div><div class="city-hud-stat" aria-label="Code Coins"><span class="big coin">🪙</span><span id="city-coin-count">${state.coins.toLocaleString()}</span><button class="city-plus" type="button" data-bonus="coins" aria-label="How to earn Code Coins">+</button></div><button class="city-settings" id="city-settings" type="button" aria-label="Sound settings">⚙</button></header>`}
const icons={lessons:'<svg viewBox="0 0 28 28" fill="none" stroke="currentColor" stroke-width="2.2"><path d="M14 6Q8 2 3 5v17q6-2 11 2 5-4 11-2V5q-5-3-11 1v18"/></svg>',courses:'<svg viewBox="0 0 28 28" fill="none" stroke="currentColor" stroke-width="2.1"><path d="m2 10 12-6 12 6-12 6L2 10Zm4 4v6q8 5 16 0v-6"/></svg>',playground:'<svg viewBox="0 0 28 28" fill="none" stroke="currentColor" stroke-width="2"><path d="M7 8h14a5 5 0 0 1 5 5l1 7q-1 6-6 1l-3-3h-8l-3 3q-5 5-6-1l1-7a5 5 0 0 1 5-5ZM8 11v8m-4-4h8m8-2h1m2 3h1"/></svg>',progress:'<svg viewBox="0 0 28 28" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><path d="M5 23v-8m7 8V5m7 18V11m6 12v-5"/></svg>',pet:'<svg viewBox="0 0 28 28" fill="none" stroke="currentColor" stroke-width="2"><path d="m5 13-1-9 7 4a12 12 0 0 1 6 0l7-4-1 9a10 10 0 1 1-18 0ZM10 15h.1m8 0h.1M12 19q2 2 4 0"/></svg>'};
function nav(){return `<nav class="city-bottom-nav" aria-label="Main navigation">${[['lessons','Lessons'],['courses','Courses'],['playground','Playground'],['progress','Progress'],['pet','My Pet']].map(([key,label])=>`<button type="button" class="city-nav-btn ${key==='lessons'?'active':''}" data-tab="${key}" ${key==='lessons'?'aria-current="page"':''}><span class="symbol">${icons[key]}</span><span>${label}</span></button>`).join('')}</nav>`}
function flash(message){let toast=root.querySelector('.city-toast');if(!toast){toast=document.createElement('div');toast.className='city-toast';toast.setAttribute('role','status');root.querySelector('.city-shell')?.appendChild(toast);}toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toast.hidden=true},3200)}
function progressPadClass(item){if(state.completed.includes(item.number))return 'is-complete';if(state.cleared.includes(item.number))return 'is-cleared';if(item.number===activeNum)return 'is-current';return 'is-locked'}
function drawPanel(segment){
 const {zone,items,first}=segment;
 const positions=items.length===1?[{x:.52,y:.40}]:items.length===2?[{x:.50,y:.80},{x:.55,y:.30}]:items.length===3?[{x:.51,y:.86},{x:.69,y:.54},{x:.45,y:.25}]:[{x:.51,y:.88},{x:.73,y:.69},{x:.44,y:.48},{x:.58,y:.25}];
 let controls=items.map((node,i)=>{
  const pos=positions[i],cls=progressPadClass(node),complete=state.completed.includes(node.number),currentNode=node.number===activeNum;
  const label=node.kind==='boss'?'Boss Build checkpoint':node.lesson.title;
  return `<button class="city-pad ${cls} ${node.kind==='boss'?'is-boss':''}" type="button" data-level="${node.number}" aria-label="Level ${node.number}. ${escapeText(label)}. ${cls.replace('is-','')}" style="left:${pos.x*100}%;top:${pos.y*100}%"><span>${node.number}</span>${node.kind==='boss'?'<span class="boss-diamond" aria-hidden="true">✦</span>':''}${complete?'<span class="check" aria-hidden="true">✓</span>':''}${currentNode?`<img class="city-active-pet ${state.evolution?'is-evolved':''}" src="./pet-map-${chosenPet}.png" alt="${PET_NAMES[chosenPet]} hovering over current level" loading="lazy">`:''}</button>`}).join('');
 const sign=first?`<div class="city-road-sign" style="--accent:${zone.accent}" aria-label="${zone.sign} ${zone.name}"><small>${zone.sign}</small>${zone.name.toUpperCase()}${segment.comingSoon?'<small style="margin-top:6px;font-size:11px">MORE LESSONS TO COME</small>':''}</div>`:'';
 return `<section class="city-panel ${zone.id}" data-zone="${zone.id}" aria-label="${zone.name}" style="--accent:${zone.accent}">${sign}${controls}</section>`;
}
function escapeText(str){return String(str).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function assembleMap(){savePet();checkDay();activeNum=current();const panels=[...segments].reverse().map(drawPanel).join('');root.innerHTML=`<div class="city-shell">${hud()}<div class="city-scroll" id="city-scroll"><div class="city-world">${panels}</div></div><button class="city-return" type="button" id="city-return">⌖ &nbsp;Return to My Level</button>${nav()}</div>`;scrollPort=root.querySelector('#city-scroll');mapWorld=root.querySelector('.city-world');screen='map';bindCommon();bindMap();
 requestAnimationFrame(()=>{if(returnAfterCelebration){if(transitionFromNum!==null)animatePetToNext(transitionFromNum,activeNum);else scrollToCurrent(true);transitionFromNum=null;returnAfterCelebration=false}else if(lastViewport>0){scrollPort.scrollTop=lastViewport;updateReturn()}else scrollToCurrent(false)});
}
function scrollToCurrent(smooth){const pad=root.querySelector(`.city-pad[data-level="${activeNum}"]`);if(!pad||!scrollPort)return;let top=pad.getBoundingClientRect().top-scrollPort.getBoundingClientRect().top+scrollPort.scrollTop-scrollPort.clientHeight*.52;scrollPort.scrollTo({top:Math.max(0,top),behavior:smooth&&!matchMedia('(prefers-reduced-motion: reduce)').matches?'smooth':'instant'});}
function animatePetToNext(fromNum,toNum){
 const from=root.querySelector(`.city-pad[data-level="${fromNum}"]`),to=root.querySelector(`.city-pad[data-level="${toNum}"]`);
 if(!from||!to||from===to||matchMedia('(prefers-reduced-motion: reduce)').matches){scrollToCurrent(false);return;}
 // Show the previous pad in place; the chosen pet itself glides above the road as
 // the camera follows toward the next pad. The artwork never changes identity.
 const oldTop=from.getBoundingClientRect().top-scrollPort.getBoundingClientRect().top+scrollPort.scrollTop-scrollPort.clientHeight*.57;
 scrollPort.scrollTop=Math.max(0,oldTop);
 const target=to.querySelector('.city-active-pet');if(target)target.style.visibility='hidden';
 const ghost=document.createElement('img');ghost.className='city-floating-pet';ghost.alt='';ghost.src='./pet-map-'+chosenPet+'.png';ghost.style.transition='none';root.querySelector('.city-shell').appendChild(ghost);
 let start=from.getBoundingClientRect(),startX=start.left+start.width/2-55,startY=start.top-113,begin=performance.now();
 scrollToCurrent(true);
 function frame(t){const duration=1150,p=Math.min(1,(t-begin)/duration),e=p*p*(3-2*p),dest=to.getBoundingClientRect();
  // Destination changes every frame while the user-view scroll animates.
  ghost.style.left=(startX+(dest.left+dest.width/2-55-startX)*e)+'px';
  ghost.style.top=(startY+(dest.top-113-startY)*e-11*Math.sin(p*Math.PI))+'px';
  if(p<1)requestAnimationFrame(frame);else{ghost.remove();if(target)target.style.visibility='visible';updateReturn()}
 }
 requestAnimationFrame(frame);
}
function updateReturn(){const pad=root.querySelector(`.city-pad[data-level="${activeNum}"]`);const rb=root.querySelector('#city-return');if(!pad||!rb||!scrollPort)return;const a=pad.getBoundingClientRect(),b=scrollPort.getBoundingClientRect();rb.classList.toggle('show',a.top<b.top+30||a.top>b.bottom-35)}
function bindCommon(){root.querySelectorAll('[data-bonus]').forEach(b=>b.addEventListener('click',()=>flash(b.dataset.bonus==='heart'?'Earn blue hearts through reviews or wait 20 minutes per heart.':'Earn Code Coins by completing lessons and Boss Builds.')));root.querySelector('#city-settings')?.addEventListener('click',()=>{state.mute=!state.mute;storage();flash(state.mute?'Sound muted.':'Sound effects enabled.');});root.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='lessons'){if(location.hash!=='#/city')location.hash='/city';else scrollToCurrent(true)}else flash('We’ll build this screen from your approved screenshot next.');}));}
function bindMap(){root.querySelectorAll('[data-level]').forEach(p=>p.addEventListener('click',()=>{const id=Number(p.dataset.level),node=byNumber.get(id);if(node.planned){flash('This town’s lessons are being developed.');return;}if(canVisit(node)){lastViewport=scrollPort.scrollTop;location.hash='/lesson/'+id;}else{let prior=byNumber.get(activeNum);flash(`${PET_NAMES[chosenPet]}: Complete Level ${activeNum} first!`);}}));root.querySelector('#city-return').addEventListener('click',()=>scrollToCurrent(true));scrollPort.addEventListener('scroll',updateReturn,{passive:true});}
function showProgress(){screen='progress';const zoneCards=ZONES.map(z=>{const all=nodes.filter(n=>n.zone.id===z.id),count=all.filter(n=>state.completed.includes(n.number)||state.cleared.includes(n.number)).length;return `<div class="city-lesson-card"><strong>${z.name}</strong><p>${count} of ${all.length} levels reached</p><progress max="${all.length}" value="${count}" style="width:100%;accent-color:#30ddfa"></progress></div>`}).join('');root.innerHTML=`<div class="city-shell">${hud()}<div class="city-scene" style="position:relative;inset:auto;flex:1"><button class="city-secondary" id="city-back">← Code City</button><h1>Progress</h1><div class="city-lesson-card"><b>★ ${state.xp} XP</b> &nbsp; 🪙 ${state.coins} Coins</div>${zoneCards}</div>${nav()}</div>`;bindCommon();root.querySelector('#city-back').onclick=()=>location.hash='/city';}
function takeHeart(){syncHearts();if(state.hearts>=3)state.heartsAt=Date.now();state.hearts=Math.max(0,state.hearts-1);storage();let e=root.querySelector('#city-heart-count');if(e)e.textContent=String(state.hearts);}
function showReview(){const lessons=bodyData.lessons.filter(l=>state.completed.some(n=>byNumber.get(n)?.lesson?.id===l.id));const lesson=lessons.at(-1);if(!lesson){flash('Hearts return automatically, one every 20 minutes.');return;}const question=lesson.quiz[0];if(!question){flash('One heart returns every 20 minutes.');return;}root.querySelector('#city-lesson-content').innerHTML=`<div class="city-lesson-card"><h2>Quick Review 💙</h2><p>${escapeText(question.q)}</p>${question.options.map((o,i)=>`<button type="button" class="city-quiz-option" data-review-answer="${i}">${escapeText(o)}</button>`).join('')}<p>Complete this review to restore one heart.</p></div>`;root.querySelectorAll('[data-review-answer]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.reviewAnswer)===question.answer){state.hearts=Math.min(3,state.hearts+1);state.heartsAt=Date.now();storage();flash('Great review! +1 blue heart.');showLesson(byNumber.get(Number(location.hash.split('/').at(-1))))}else flash(`${PET_NAMES[chosenPet]}: Not quite—think about the lesson and try again.`)});}
function showLesson(node){if(!node||node.planned){location.hash='/city';return;}screen='lesson';let lesson=node.lesson||null,boss=node.kind==='boss';root.innerHTML=`<div class="city-shell">${hud()}<div class="city-scene" style="position:relative;inset:auto;flex:1"><button type="button" id="city-back" class="city-secondary">← Code City</button><div id="city-lesson-content"></div></div>${nav()}</div>`;bindCommon();root.querySelector('#city-back').onclick=()=>location.hash='/city';if(boss)showBoss(node);else showLessonStages(node);}
function showLessonStages(node){const lesson=node.lesson;let stage=0, code=lesson.starter||'',responses=[],quizIndex=0;const el=root.querySelector('#city-lesson-content');
function base(){return `<div class="city-breadcrumb">${node.zone.name} &nbsp;→&nbsp; Level ${node.number}</div><h1 class="city-lesson-heading">${escapeText(lesson.title)}</h1><div style="margin:8px 0 12px"><span class="city-step-dot ${stage===0?'active':''}">1</span><span class="city-step-dot ${stage===1?'active':''}">2</span><span class="city-step-dot ${stage===2?'active':''}">3</span></div>`}
function intro(){stage=0;el.innerHTML=base()+`<div class="city-lesson-card"><img class="city-lesson-pet" src="./pet-map-${chosenPet}.png" alt="${PET_NAMES[chosenPet]}"><h2>Let’s learn!</h2><p>${escapeText(lesson.concept)}</p>${lesson.steps.map(t=>`<p>✦ ${escapeText(t)}</p>`).join('')}<div class="city-preview"><code>${escapeText(lesson.example)}</code></div></div><button class="city-primary" id="lesson-next">Your turn →</button>`;el.querySelector('#lesson-next').onclick=practice;}
function practice(){stage=1;el.innerHTML=base()+`<div class="city-lesson-card"><img class="city-lesson-pet" src="./pet-map-${chosenPet}.png" alt=""><h2>Your turn!</h2><p>${escapeText(lesson.task)}</p><textarea class="city-code-editor" id="lesson-code" spellcheck="false" aria-label="Write your code">${escapeText(code)}</textarea><div style="display:flex;flex-wrap:wrap;gap:6px;margin:10px 0">${['<','>','/','=','"','(',')','{','}',';'].map(t=>`<button class="city-secondary" style="padding:6px 11px" data-symbol="${escapeText(t)}">${escapeText(t)}</button>`).join('')}</div><p class="city-error" id="lesson-hint" aria-live="polite"></p><button class="city-secondary" id="lesson-help">Hint</button> <button class="city-primary" id="lesson-check">Check →</button></div>`;
const txt=el.querySelector('#lesson-code');el.querySelectorAll('[data-symbol]').forEach(b=>b.onclick=()=>{let s=txt.selectionStart,e=txt.selectionEnd,symbol=b.dataset.symbol;txt.value=txt.value.slice(0,s)+symbol+txt.value.slice(e);txt.focus();txt.setSelectionRange(s+symbol.length,s+symbol.length)});
let hint=0;el.querySelector('#lesson-help').onclick=()=>{el.querySelector('#lesson-hint').textContent=lesson.hints[Math.min(hint++,lesson.hints.length-1)]};
el.querySelector('#lesson-check').onclick=()=>{code=txt.value;const rules=lesson.rules||[];let invalid;for(const r of rules){try{if(!new RegExp(r.value,'im').test(code)){invalid=r.message;break}}catch(_){invalid='Check your syntax and try again.';break}}if(invalid){takeHeart();el.querySelector('#lesson-hint').textContent=state.hearts===0?'Out of hearts! Complete a review or wait for a refill.':`${PET_NAMES[chosenPet]}: ${lesson.hints[Math.min(hint++,lesson.hints.length-1)]||invalid}`;if(state.hearts===0){el.querySelector('#lesson-check').disabled=true;let rev=document.createElement('button');rev.className='city-primary';rev.textContent='Quick Review to earn a heart';rev.onclick=showReview;el.querySelector('.city-lesson-card').appendChild(rev)}return;}quiz();};}
function quiz(){stage=2;if(state.hearts===0){showReview();return;}const q=lesson.quiz[quizIndex];if(!q){const passed=responses.filter(x=>x).length/Math.max(1,responses.length)>=.8;if(passed)completeLevel(node);else{flash('Review the lesson and retake the quiz.');quizIndex=0;responses=[];intro()}return;}let answer=null;el.innerHTML=base()+`<div class="city-lesson-card"><img class="city-lesson-pet" src="./pet-map-${chosenPet}.png" alt=""><h2>Quick Quiz</h2><p>Question ${quizIndex+1} of ${lesson.quiz.length}</p><h3>${escapeText(q.q)}</h3>${q.options.map((v,i)=>`<button type="button" class="city-quiz-option" data-answer="${i}">${escapeText(v)}</button>`).join('')}<p class="city-error" id="quiz-hint" aria-live="polite"></p><button class="city-primary" id="quiz-next">Check answer</button></div>`;
el.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{answer=Number(b.dataset.answer);el.querySelectorAll('[data-answer]').forEach(o=>o.classList.toggle('selected',o===b))});
el.querySelector('#quiz-next').onclick=()=>{if(answer===null){el.querySelector('#quiz-hint').textContent='Choose an answer first.';return;}if(answer!==q.answer){takeHeart();el.querySelector('#quiz-hint').textContent=`${PET_NAMES[chosenPet]}: Here’s a hint—think back to the example! Try again.`;if(state.hearts===0){el.querySelector('#quiz-next').disabled=true;const b=document.createElement('button');b.className='city-primary';b.textContent='Quick Review';b.onclick=showReview;el.querySelector('.city-lesson-card').appendChild(b)}return;}responses.push(true);quizIndex++;quiz();};}
intro();}
function showBoss(node){const track=node.zone.id;if(!['html','css','js'].includes(track)){flash('This Boss Build is still in development.');return;}let drafts=state.bossDrafts,project=state.project;let hint=track==='html'?'Create your website using a heading, paragraph, and button.':track==='css'?'Style the same website with a body rule and at least one color or layout rule.':'Make the website interactive using addEventListener.';let defaultCode=track==='html'?project.html||'<!doctype html>\n<html>\n<body>\n  <h1>My website</h1>\n  <p>Welcome!</p>\n  <button>Click me</button>\n</body>\n</html>':track==='css'?project.css||'body {\n  background: #dff6ff;\n  color: #12345c;\n}\nbutton { padding: 12px; }':project.js||'document.querySelector("button").addEventListener("click", () => {\n  alert("Hello!");\n});';
const el=root.querySelector('#city-lesson-content');el.innerHTML=`<div class="city-breadcrumb">${node.zone.name} • Boss Build</div><h1 class="city-lesson-heading">Build your growing website ✨</h1><div class="city-lesson-card"><p>${hint}</p><p>Your code will be saved and used again in the next town.</p><textarea class="city-code-editor" id="boss-code" style="min-height:240px" spellcheck="false">${escapeText(drafts[track]||defaultCode)}</textarea><p id="boss-status" style="color:#8feaff">Saved locally on this device.</p><div style="display:flex;gap:9px;flex-wrap:wrap"><button class="city-secondary" id="boss-save">Save draft</button><button class="city-primary" id="boss-check">Finish Boss Build →</button></div><p class="city-error" id="boss-hint"></p></div>`;
const ta=el.querySelector('#boss-code'),status=el.querySelector('#boss-status');function save(){drafts[track]=ta.value;storage();status.textContent='Draft saved on this device ✓';}let deb;ta.addEventListener('input',()=>{status.textContent='Saving…';clearTimeout(deb);deb=setTimeout(save,450)});el.querySelector('#boss-save').onclick=save;el.querySelector('#boss-check').onclick=()=>{save();let valid=track==='html'?/<h1\b[^>]*>.*?<\/h1>/is.test(ta.value)&&/<p\b[^>]*>.*?<\/p>/is.test(ta.value)&&/<button\b/is.test(ta.value):track==='css'?/body\s*\{[^}]+\}/is.test(ta.value)&&/[\w-]+\s*:\s*[^;}{]+/i.test(ta.value):/addEventListener\s*\(/.test(ta.value);if(!valid){el.querySelector('#boss-hint').textContent=`${PET_NAMES[chosenPet]}: ${hint}`;return;}project[track]=ta.value;storage();completeLevel(node);};}
function completeLevel(node){if(state.completed.includes(node.number)){location.hash='/city';return;}const boss=node.kind==='boss';state.completed.push(node.number);state.xp+=boss?160:40;state.coins+=boss?60:8;if(boss){state.evolution=ZONES.findIndex(z=>z.id===node.zone.id)+1;}else{checkDay();state.newToday++;if(state.newToday===4&&state.dailyBonusDay!==state.day){state.dailyBonusDay=state.day;state.xp+=60;state.coins+=20;}}storage();const next=nodes.find(x=>!state.completed.includes(x.number)&&!state.cleared.includes(x.number));activeNum=next?.number||node.number;transitionFromNum=node.number;
root.querySelector('.city-shell')?.insertAdjacentHTML('beforeend',`<div class="city-celebrate" id="city-celebrate"><h1>${boss?'TOWN COMPLETE! 🎉':'LEVEL COMPLETE! ✨'}</h1><img src="./pet-map-${chosenPet}.png" alt="${PET_NAMES[chosenPet]} celebrates"><p>${escapeText(node.zone.name)} • Level ${node.number}</p><h2>+${boss?160:40} XP &nbsp; +${boss?60:8} Coins</h2>${boss?'<p>Town complete! Your pet evolves and your next town unlocks.</p>':''}<p style="color:#b5f4ff">Returning to Code City…</p></div>`);
setTimeout(()=>{returnAfterCelebration=true;lastViewport=0;location.hash='/city';if(location.hash==='#/city')assembleMap()},boss?3300:2200);
}
function route(){const h=location.hash;if(h==='#/city'){assembleMap()}else if(h.startsWith('#/lesson/')){const number=Number(h.split('/').at(-1)),node=byNumber.get(number);if(!node||node.planned||!canVisit(node)){location.hash='/city';return;}checkDay();if(!state.completed.includes(number)&&node.kind==='lesson'&&state.newToday>=4){assembleMap();flash('Four new lessons today! Review or do an unlocked Boss Build.');return;}showLesson(node)} }
root.addEventListener('click',e=>{ /* non-interactive background intentionally ignores all taps */ });
window.CodeCity={route,show:route,goToCurrent:()=>scrollToCurrent(true),getState:()=>structuredClone(state),getNodes:()=>nodes.map(x=>({number:x.number,zone:x.zone.id,kind:x.kind,planned:x.planned}))};
addEventListener('hashchange',()=>{if(location.hash==='#/city'||location.hash.startsWith('#/lesson/'))route()});
if(location.hash==='#/city'||location.hash.startsWith('#/lesson/'))route();
})();
